
CREATE TABLE MEMBER(
MNO         NUMBER              UNIQUE NOT NULL,
MNAME       VARCHAR2(40)        NOT NULL,
EMAIL       VARCHAR2(100)       PRIMARY KEY,
PWD         VARCHAR2(50)        NOT NULL,
MCREDATE    DATE                NOT NULL
);
CREATE SEQUENCE MEMBER_NO_SEQ
INCREMENT BY 1
START WITH 1;

CREATE TABLE BOARD(
BNO         NUMBER        NOT NULL,
TITLE       VARCHAR2(100) NOT NULL,
WRITER      VARCHAR2(50) NOT NULL, --EMAIL
CONTENT     VARCHAR2(4000) NOT NULL,
BCREDATE    DATE        NOT NULL

);

CREATE SEQUENCE BOARD_NO_SEQ
INCREMENT BY 1
START WITH 1;

ALTER TABLE BOARD
ADD CONSTRAINTS BOARD_WRITER_FK FOREIGN KEY (WRITER) REFERENCES MEMBER(EMAIL);


--테이블당 데이터 1가지씩 입력해보기!
INSERT INTO MEMBER
(NO,NAME,EMAIL,PWD,CREDATE)
VALUES
(MEMBER_NO_SEQ.NEXTVAL,'정혜미','HMJ@aa.com',1111,SYSDATE);

INSERT INTO BOARD
(NO,TITLE,WRITER,CONTENT,CREDATE)
VALUES
(BOARD_NO_SEQ.NEXTVAL,'첫번째 글','HMJ@aa.com','이얏호 JLProject 게시판의 첫번째 글이다!',SYSDATE);
--오류가 나도 NEXTVAL은 올라감..ㅠㅠ

SELECT * FROM MEMBER;
SELECT * FROM BOARD;
